# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Coolieyah\Semester 6\PemVis\pv25-week4\kasir.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(355, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBoxProduk = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxProduk.setGeometry(QtCore.QRect(130, 20, 161, 22))
        self.comboBoxProduk.setObjectName("comboBoxProduk")
        self.comboBoxProduk.addItem("")
        self.comboBoxProduk.addItem("")
        self.comboBoxProduk.addItem("")
        self.comboBoxProduk.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 55, 16))
        self.label.setObjectName("label")
        self.lineEditJumlah = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditJumlah.setGeometry(QtCore.QRect(130, 60, 161, 22))
        self.lineEditJumlah.setObjectName("lineEditJumlah")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 100, 55, 16))
        self.label_3.setObjectName("label_3")
        self.comboBoxDiskon = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxDiskon.setGeometry(QtCore.QRect(130, 100, 91, 22))
        self.comboBoxDiskon.setObjectName("comboBoxDiskon")
        self.comboBoxDiskon.addItem("")
        self.comboBoxDiskon.addItem("")
        self.comboBoxDiskon.addItem("")
        self.comboBoxDiskon.addItem("")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(60, 140, 93, 28))
        self.btnAdd.setObjectName("btnAdd")
        self.btnClr = QtWidgets.QPushButton(self.centralwidget)
        self.btnClr.setGeometry(QtCore.QRect(200, 140, 93, 28))
        self.btnClr.setObjectName("btnClr")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 190, 231, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.labelTotal = QtWidgets.QLabel(self.centralwidget)
        self.labelTotal.setGeometry(QtCore.QRect(60, 310, 211, 16))
        self.labelTotal.setObjectName("labelTotal")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 340, 231, 20))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 355, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kasir Sederhana"))
        self.comboBoxProduk.setItemText(0, _translate("MainWindow", "-select-"))
        self.comboBoxProduk.setItemText(1, _translate("MainWindow", "Tahu (Rp.2000)"))
        self.comboBoxProduk.setItemText(2, _translate("MainWindow", "Tempe (Rp.4000)"))
        self.comboBoxProduk.setItemText(3, _translate("MainWindow", "Ikan (Rp.10,000)"))
        self.label.setText(_translate("MainWindow", "Product"))
        self.label_2.setText(_translate("MainWindow", "Quantity"))
        self.label_3.setText(_translate("MainWindow", "Discount"))
        self.comboBoxDiskon.setItemText(0, _translate("MainWindow", "0%"))
        self.comboBoxDiskon.setItemText(1, _translate("MainWindow", "10%"))
        self.comboBoxDiskon.setItemText(2, _translate("MainWindow", "50%"))
        self.comboBoxDiskon.setItemText(3, _translate("MainWindow", "70%"))
        self.btnAdd.setText(_translate("MainWindow", "Add To Cart"))
        self.btnClr.setText(_translate("MainWindow", "Clear"))
        self.labelTotal.setText(_translate("MainWindow", "Total : Rp.0"))
        self.label_4.setText(_translate("MainWindow", "Lalu Muhammad Noval A. - F1D022056"))
